site_name: SPRING Lab Documentation
repo_name: SPRING Lab
repo_url: https://github.com/spring-iitd/

plugins:
  - search
  - meta

theme:
  name: material
  custom_dir: overrides
  favicon: ./imgs/logo-circle.png
  logo: ./imgs/logo-circle.png
  icon:
    repo: fontawesome/brands/github
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  homepage: https://spring.iitd.ac.in

nav:
    - About: "index.md"
    - 'Proxy Login':
        - 'Setting up Proxy': "proxy_setup.md"
        - 'Logging In': "internet_on_vm.md"
        - 'Internet on Terminal': "internet_on_my_terminal.md"
    - 'Working with Docker':
        - 'Installing Docker': "docker_install.md"
        - 'Docker Config': "docker_proxy_settings.md"
    - 'SSH : Working remotely': "living_life_in_an_ssh_session.md"
    - 'Package Installation (APT)' : "package_installation.md"
    - 'Using HPC': 'using_hpc.md'
    - 'Using Conda': 'using_conda.md'
    - 'Raspberry Pi': "wifi_on_raspberry_pi.md"
    - 'Git config': "git_errors.md"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences